= Planning for Bike Rides from London

== Routes

=== Lanes 3

==== Strava Bike Routes

https://www.strava.com/athlete/routes[If you use Strava, your routes should be here]

===== Orpington Ightham return

https://www.strava.com/routes/3089931437965089844[IGHT-ORP (14.9)]

https://www.strava.com/routes/3089918939211140634[ORP-IGHT (15.6)]

===== Others

https://www.strava.com/routes/3090071398187569168[Dul-NWD]

https://www.strava.com/routes/3090040279279305744[Lanes3]

== Live Departure Boards

https://ojp.nationalrail.co.uk/service/ldbboard/dep/NHD[Live from Nunhead]

https://ojp.nationalrail.co.uk/service/ldbboard/dep/WDU[Live from West Dulwich]

https://ojp.nationalrail.co.uk/service/ldbboard/dep/ORP[Live from Orpington]

https://ojp.nationalrail.co.uk/service/ldbboard/dep/ECR[Live from East Croydon]

https://ojp.nationalrail.co.uk/service/ldbboard/dep/NWD[Live from Norwood Junction]

https://ojp.nationalrail.co.uk/service/ldbboard/dep/LFD[Live from Lingfield]

https://www.nationalrail.co.uk/times_fares/ldb.aspx[National Rail Live departures]

==== Trains timetables Scheduled Departures

===== Today

https://ojp.nationalrail.co.uk/service/timesandfares/WDU/ORP/today/1015/dep/today/1530/dep[WDU/ORP National Rail today dep 10:15]

https://ojp.nationalrail.co.uk/service/timesandfares/NWD/LFD/today/1030/dep/today/1230/dep[NWD/LFD National Rail today departing 10:30]

https://ojp.nationalrail.co.uk/service/timesandfares/DMK/SAY/today/1030/dep[DMK/SAY National Rail today departing 10:30]


===== Tomorrow

https://ojp.nationalrail.co.uk/service/timesandfares/ECR/LFD/tomorrow/1030/dep/tomorrow/1530/dep[ECR/LFD National Rail Tomorrow dep 10:30]

https://ojp.nationalrail.co.uk/service/timesandfares/WDU/ORP/tomorrow/1015/dep/tomorrow/1530/dep[WDU/ORP National Rail Tomorrow dep 10:15]

==== Cut down

[cols="1,1,1,1"]
|===
|From|To|Dep|Arr

|WDU
|ORP
|10:40
|11:09

|WDU
|ORP
|11:10
|11:39

|ECR
|LFD
|11:10
|11:41

|LFD
|ECR
|16:13
|16:45

|LFD
|ECR
|16:43
|17:14


|===

=== Norwood Junction to Lingfield seems to have been cut from the timetable

[cols="1,1,1,1"]
|===
|From|To|Dep|Arr



|NWD
|LFD
|10:37
|11:11

|NWD
|LFD
|11:07
|11:44


|LFD
|NWD
|15:19
|15:57


|LFD
|NWD
|15:49
|16:28


|===

==== Timings

[cols="1,1,1,1"]
|===

|Section|Distance|Climb|Duration

|Dulwich ECR
|12 km
|100 m
|0:50

|Dulwich NWD
|7.35 km
|97 m
|0:24

|NWD/LFD
|X
|X
|0:37

|Ride
|41.35 km
|575 m
|2:12

|LFD/NWD
|X
|X
|0:37

|NWD Dulwich
|4.7 mile
|300 ft
|0:30

|Total
|X
|X
|4:30


|===


== Cut down timetable

[cols="1,1,1,1"]
|===
|From|To|Dep|Arr

|DMK
|SAY
|10:54
|11:30

|DMK
|SAY
|11:02
|11:30

|DMK
|SAY
|11:24
|12:00

|WDU
|ORP
|10:10
|10:39

|WDU
|ORP
|10:40
|11:09

|WDU
|ORP
|11:10
|11:39

|WDU
|ORP
|11:40
|12:09

|ORP
|WDU
|15:54
|16:20

|ORP
|WDU
|16:24
|16:50

|ORP
|WDU
|16:54
|17:20

|ORP
|WDU
|17:24
|17:50

|NWD
|LFD
|10:37
|11:11

|NWD
|LFD
|11:07
|11:44


|LFD
|NWD
|15:19
|15:57


|LFD
|NWD
|15:49
|16:28


|===



== Station Codes

[cols="1,1"]
|===
|Code|Station

|DMK
|Denmark Hill

|PMR
|Peckham Rye

|NHD
|Nunhead

|HNH
|Herne Hill

|BMS
|Bromley South 

|BKJ
|Beckenham Junction

|SAY
|Swanley

|ORP
|Orpington

|WDU
|West Dulwich

|NWD
|Norwood Junction

|LFD
|Lingfield

|ECR
|East Croydon

|LBG
|London Bridge

|EGR
|East Grinstead

|VIC
|London Victoria

|===


== Train fares

NWD to LFD return £12.50
